# Generated by Django 3.0.5 on 2020-05-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200429_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=51)),
                ('email', models.CharField(max_length=51)),
                ('phone', models.CharField(default='', max_length=51)),
                ('desc', models.CharField(default='', max_length=511)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_price',
            field=models.IntegerField(default=0),
        ),
    ]
